export const INCREMENT_ENTHUSIASM = "INCREMENT_ENTHUSIASM";
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM";
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const RESET_ENTHUSIAM = "RESET_ENTHUSIASM";
export type RESET_ENTHUSIAM = typeof RESET_ENTHUSIAM;
